spring:
  application:
    name: spring-ai-rag-example
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo

app:
  resource: https://en.wikipedia.org/wiki/Chess
